### ISSUE TITLE
Power flow calculation of AC/DC system

### ISSUE THREAD

**Issue by YaeSakura1** [cuihantao/andes#102]
Respected Professor Hantao Cui：
  I am a postgraduate student from Kunming University of Science and Technology, Yunnan Province, China. I would like to use your Andes software to realize the function of ac/DC power flow calculation.
  I would be grateful if you could give me some valuable advice on whether this is possible.
  Thank you very much

**Comment by cuihantao** [comment]
Hello @YaeSakura1,

You can start by looking at the example data file under `cases/kundur/kundur_vsc.xlsx`. The file defines DC Nodes, resistive lines, and voltage source converters (VSCShunt).

You can checkout the source code for `VSCShunt`, which can be a starting point for adding your own model.

What particular elements are you looking to add for AC/DC power flow?

**Comment by cuihantao** [comment]
I’m closing the issue for now. Feel free to reopen it.

**Comment by YaeSakura1** [comment]
Professor Cui Hantao:
Sorry for replying your email so late. Thank you for your suggestions and guidance.

I would like to ask you whether you have the system connection diagram of the kundur_vsc.xlsx transformed with the kundur four gernerator and two areas, or I need to draw the wiring diagram according to the table data.

I hope to add LCC and MMC models, it would be better if we can realize multi-terminal mixed DC and MMC-HVDC, and realize power flow calculation of AC-DC system

Thank you again
