### ISSUE TITLE
Set unit field of trans parameter on Line to bool

### ISSUE THREAD

**Issue by rwl** [cuihantao/andes#110]
Should the `trans` parameter on the `Line` model have unit `bool`?

https://github.com/cuihantao/andes/blob/3da707a78a9a97326973f90ed68a28e311327851/andes/models/line.py#L31

Similar to the `u` parameter on the `ModelData` class:

https://github.com/cuihantao/andes/blob/3da707a78a9a97326973f90ed68a28e311327851/andes/core/model.py#L197

**Comment by cuihantao** [comment]
Fixed in afeffce. Updated units for all line parameters.

https://github.com/cuihantao/andes/blob/afeffceb8a3a17274a90f061acbe361c54c66d20/andes/models/line.py#L88-L93
