### ISSUE TITLE
Power flow calculation of AC/DC system

### ISSUE THREAD

**Issue by YaeSakura1** [cuihantao/andes#111]
Professor Cui Hantao:
Sorry for replying your email so late. Thank you for your suggestions and guidance.

I would like to ask you whether you have the system connection diagram of the kundur_vsc.xlsx transformed with the kundur four gernerator and two areas, or I need to draw the wiring diagram according to the table data.

I hope to add LCC and MMC models, it would be better if we can realize multi-terminal mixed DC and MMC-HVDC, and realize power flow calculation of AC-DC system

Thank you again

_Originally posted by @YaeSakura1 in https://github.com/cuihantao/andes/issues/102#issuecomment-744133712_

**Comment by cuihantao** [comment]
YaeSakura1,

I don't have the diagram of the kundur system at hand. You can find the original Kundur's system online and draw it out by hand. Simply draw the DC Nodes like AC Buses, and use the bus and node information in the VSCShunt page to link buses to nodes.

In power flow, one wouldn't care about the type of the HVDC. They are simply treated as power injections. There are models for LLC in transient dynamic simulation. But to simulate the switching in MMC, you will need an electromagnetic simulation tool.
