### ISSUE TITLE
play in signal to a network

### ISSUE THREAD

**Issue by 1rashiid** [cuihantao/andes#114]
Does andes have a function as a playback function in PSSE or powerworld? I want to create a model which includes a generator, pss, governor, and an exciter. I want to insert the voltage and frequency into the network and get the real and reactive power as output. Is that possible with andes? thanks

**Comment by cuihantao** [comment]
Hi @1rashiid ,

This feature is not currently supported but worth doing. I will assign an enhancement label for the issue. 

Does Powerworld or PSS/E allow replaying any variable data or a specific set (say, voltages, frequency among others)?

**Comment by cuihantao** [comment]
I found the slides at https://www.wecc.org/Reliability/Wkshp_ATC_Playback_Model_Validation.pptx. Is it the `PLBVFU1` model that specifically implements the requested function?

**Comment by 1rashiid** [comment]
Yes. The concept is known as "playback event" and it is used for model validation and calibration. The PMU catches the dynamic of the system. Then, voltage, and voltage phase (or frequency) are play into the model and real and reactive are computed and compared with the P and Q which capture with PMU. This function is "plbvfu1" in PSSE. There are some paper which explain this concept also:
1- Response-Surface-Based Bayesian Inference for Power System Dynamic Parameter Estimation
2- Calibrating Parameters of Power System Stability Models Using Advanced Ensemble Kalman Filter
3- PMU Measurement Based Generator Parameter Calibration by Black-Box Optimization with A Stochastic Radial Basis Function Surrogate Model

**Comment by 1rashiid** [comment]
> I found the slides at https://www.wecc.org/Reliability/Wkshp_ATC_Playback_Model_Validation.pptx. Is it the `PLBVFU1` model that specifically implements the requested function?

Yes exactly.

**Comment by cuihantao** [comment]
> Yes. The concept is known as "playback event" and it is used for model validation and calibration. The PMU catches the dynamic of the system. Then, voltage, and voltage phase (or frequency) are play into the model and real and reactive are computed and compared with the P and Q which capture with PMU. This function is "plbvfu1" in PSSE. There are some paper which explain this concept also:
> 1- Response-Surface-Based Bayesian Inference for Power System Dynamic Parameter Estimation
> 2- Calibrating Parameters of Power System Stability Models Using Advanced Ensemble Kalman Filter
> 3- PMU Measurement Based Generator Parameter Calibration by Black-Box Optimization with A Stochastic Radial Basis Function Surrogate Model

Thanks for pointing to these references. Let me look into adding this feature to ANDES.

**Comment by cuihantao** [comment]
> > I found the slides at https://www.wecc.org/Reliability/Wkshp_ATC_Playback_Model_Validation.pptx. Is it the `PLBVFU1` model that specifically implements the requested function?
> 
> Yes exactly.

Great. I don't have a clear timeline for finishing the feature though. Expect to be in a couple of months given my current workload.

**Comment by cuihantao** [comment]
Working on this currently:
[x] define a `TimeSeries` model to read time-series data from a xlsx file
* define a generator to represent the voltage behind the impedance
* develop the `PLBVFU1` model to use the data from the `.plb` file.

**Comment by cuihantao** [comment]
A `PLBVFU1` model has been implemented. It supports per unit values only for now. See the docs for limitations.

An example can be found in `andes/cases/ieee14_plbvfu1.xlsx`.

**Comment by cuihantao** [comment]
Please report back and reopen the issue if needed. Thanks.

**Comment by 1rashiid** [comment]
Thanks for adding this feature to the package.
