### ISSUE TITLE
Output format to PSSE/Matpower

### ISSUE THREAD

**Issue by jahanbani** [cuihantao/andes#132]
I would like to compare some of the results from Andes with PSSE (or Matpower). However, it seems that Andes does not provide a raw format output. Is it possible to add such feature (or does it exist and I have missed it)?

Thank you

**Comment by cuihantao** [comment]
Hi @jahanbani ,

For now, Andes does not support exporting cases to PSS/E or MATPOWER. I'm only aware of PSAT's capability of exporting cases to a legacy PSS/E raw format but not sure if other opensource tools can do it. 

You are welcome to contribute such converter to ANDES or interface ANDES to another tool that can do the work
