### ISSUE TITLE
test system format

### ISSUE THREAD

**Issue by LeZhengThu** [cuihantao/andes#142]
Dr. Cui, 
       I notice that the test system data are contained in *.raw and *.dyr files. It seems that InterPSS also uses those two extensions to define the test system. I wonder what's the original software that defined these two extensions. Where can I find the documentation of the two extensions? I'd like to convert my own system in order to use ANDES or InterPSS. Thanks.

**Comment by cuihantao** [comment]
`raw` and `dyr` are introduced by PTI PSS/E. You can find more details from PSS/E's documentations.

**Comment by LeZhengThu** [comment]
@cuihantao Thank you, Dr. Cui.

**Comment by LeZhengThu** [comment]
@cuihantao Dr. Cui, I don't have a valid PSS/E license. And I can't find the data definition and specification for the *.dyr file anywhere online. Could you please provide some documentations for the *.dyr file? Thanks.

**Comment by cuihantao** [comment]
Hi @LeZhengThu ,

The document is proprietary to Siemens PTI, so I could not share the document with you.

One way is to find trial versions of PSS/E (known as PSS/E explore). After installing the software, you can find the documents in the `DOCS` folder. Specifically, the dynamic model definitions are in `MODELS.pdf`.

You can try requesting PSSE Explore at https://new.siemens.com/global/en/products/energy/energy-automation-and-smart-grid/pss-software/psse-xplore-order-form.html
