### ISSUE TITLE
Many buses in PV and PQ are repeated in npcc case

### ISSUE THREAD

**Issue by chenggang2333** [cuihantao/andes#145]
**Describe the bug**

**To Reproduce**
2. Run '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - ANDES version (please paste the preamble from `andes`)

**pip packages (please paste the output from `pip list`)

**Additional context**

**Comment by cuihantao** [comment]
Did you forget to edit the template?

Not sure what's the exact issue with repeated PV and PQ devices. You can have multiple PQs or multiple PQs with at most one PV on any bus. Can you elaborate?

**Comment by chenggang2333** [comment]
> Did you forget to edit the template?
> 
> Not sure what's the exact issue with repeated PV and PQ devices. You can have multiple PQs or multiple PQs with at most one PV on any bus. Can you elaborate?




> Did you forget to edit the template?
> 
> Not sure what's the exact issue with repeated PV and PQ devices. You can have multiple PQs or multiple PQs with at most one PV on any bus. Can you elaborate?

There are two issues confusing me:
1) andes/andes/case/npcc/npcc.xlsx
In "PQ" and "PV" sheets, why one bus is repeated twice in the column named "bus". 
For example, the 23rd and 24th rows in "PQ" sheet; the 53rd and 54th rows in "PQ" sheet; the 55th and 56th rows in "PQ" sheet; the 4th and 5th rows in "PV" sheet.

2) The NPCC case has 140 buses, why the total number of the PQ, the PV, and the SW buses is not equal to 140?

Thank you for your response. I will be appreciative if you could share the original NPCC 140-bus system data.
