### ISSUE TITLE
andes/andes/case/npcc/npcc.xlsx In "PQ" and "PV" sheets, why one bus is repeated twice in the column named "bus".?

### ISSUE THREAD

**Issue by chenggang2333** [cuihantao/andes#146]
There are two issues confusing me:
1) andes/andes/case/npcc/npcc.xlsx
In "PQ" and "PV" sheets, why one bus is repeated twice in the column named "bus". 
For example, the 23rd and 24th rows in "PQ" sheet; the 53rd and 54th rows in "PQ" sheet; the 55th and 56th rows in "PQ" sheet; the 4th and 5th rows in "PV" sheet.

2) The NPCC case has 140 buses, why the total number of the PQ, the PV, and the SW buses is not equal to 140?

Thank you for your response. I will be appreciative if you could share the original NPCC 140-bus system data.

**Comment by cuihantao** [comment]
You can use the same issue without creating a new one.

It is a misconception to assign a "type" (PQ or PV, or Slack) for a bus. In fact, you can have multiple PQs or multiple PQs with at most one PV on any bus. Milano has a discussion in PSAT's manual (don't remember exactly where it was though).

If multiple PQs are present on the same bus, the program will combine the total P and Q. If one PV and multiple PQs are present, the net P will be calculated by subtracting the load from the generation, and the generator's Q will be calculated after offsetting the PQ's reactive power.

**Comment by chenggang2333** [comment]
In andes/andes/tests/npcc/npcc48.dm
This file lists the data about the buses and branches. The number of PQ buses is 83 and the number of PV buses is 46. The total number of the PQ. PV and Slack bus are 130. Why 10 buses are not listed in the code? Are these buses zero injection buses?

**Comment by chenggang2333** [comment]
In andes/andes/case/npcc/npcc.xlsx
I suppose that one bus cannot be a PQ and a slack bus simultaneously. In this npcc.xlsx, the bus number is 78 in the 41th row in PQ sheet, and the bus number is also 78 in Slack sheet. I was a little confused about this part. Thank you for your clarifications. ^-^

**Comment by cuihantao** [comment]
Consider "Slack" as a generator that controls V and angle. You can have such a generator and a PQ load connected to the same bus. 

Behind the scene, after the calculation, the PQ load is added to Slack's final power solution.

You can use ANDES to solve the NPCC system.

**Comment by chenggang2333** [comment]
Thanks for your explanation.
