### ISSUE TITLE
Documentation definition

### ISSUE THREAD

**Issue by jd-lara** [cuihantao/andes#261]
The variable Rq0 doesn't seem to defined in the docs for the HYGOV. Is this a service? 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/16385323/152043761-5e009802-6137-4bf6-a379-b5cdfebdd031.png">

**Comment by cuihantao** [comment]
It's `R` times `q0`, and `q0` is a ConstService `tm0 / At + qNL`.

**Comment by jd-lara** [comment]
Thanks sorry, I read it as a separate variable.
