### ISSUE TITLE
Documentation: Change TDS timeframe in interactive usage

### ISSUE THREAD

**Issue by MaKla89** [cuihantao/andes#283]
While changing the simulation timeframe is very straightforward and simple for CLI-usage (as it is part of the cheatsheet :) ) I had a somewhat unnecessarily hard time to find out how to change the simulation time in interactive usage:

`ss = andes.run('./cases/5bus/pjm5bus.xlsx', tf=50)` 

The solution is stunningly simple, but somehow I had to figure this out with trial and error as the documentation did not mention this setting anywhere else but in the configuration params (while not telling how to apply config-changes). I'm not very savvy, thus this request might be fairly stupid, but maybe other users struggled with this, too :) 

Great work, very user-friendly otherwise!

**Comment by cuihantao** [comment]
Thanks a lot for the suggestion, and sorry for the incomplete documentation.

Did you get a chance to check out the example Jupyter notebooks? They are linked at the end of the tutorial in a short paragraph. One of the examples mentioned how to set a stopping time and then resume simulations.

I will also update the tutorial soon.

Regards,
Hantao Cui

**Comment by MaKla89** [comment]
Ah no, I did not check that out yet as I usually don't use Jupyter notebooks. It's absolutely not very important to change, but it seemed like a very basic and relevant parameter for people to play around with. Thats why I was a bit lost as in "this cannot be too hard, come on, be smarter!!" ;) 

Thanks for your reply and your work!

**Comment by cuihantao** [comment]
Updated the docs in https://github.com/cuihantao/andes/commit/139ae2565891d13a9ce854cc7af6e00dce7c02a2 and added all examples to the documentation in a new section called "Scripting Examples". Hope this will reduce efforts to jump the tutorial and examples. 

Again, thanks for the feedback. Any further comments please let me know.
