### ISSUE TITLE
TGOV1N setpoint for reactive power (qref0) does not seem to be implemented in contrast to documentation

### ISSUE THREAD

**Issue by MaKla89** [cuihantao/andes#353]
Regarding the govenor-type TGOV1N and its [documentation ](https://docs.andes.app/en/latest/groupdoc/TurbineGov.html?highlight=tgov1n#tgov1n ) I was able to set `pref0` successfully, but for `qref0` this is not working. `qref0` also seems to not even appear in the rest of the TGOV1N documentation except in the introduction text where it says `Scheduling changes should write to the v fields of pref0 and qref0 in place`.

It appears that qref0 is not yet implemented or the documentation is more advanced than the code (OR I am - again - doing something wrong, I'm sorry in that case! :D)

**Comment by cuihantao** [comment]
I made a mistake when writing the docs. Scheduling changes should be set in-place for `pref0.v`. 

Turbine governor is used for controlling the valve position of the turbine to control active power. It's not capable of controlling the reactive power. Sorry for my issue, and thank for reporting. Fixes to the docs is on the way.

**Comment by MaKla89** [comment]
Ah perfect! We are looking for a way to transfer OPF-results (made in Pandapower) to our power system. For this we either need to set generator P-output and additionally either generator Q-output or a voltage-setpoint for the generators. With the `qref0` option off the table, would you have a suggestion for how to set the voltage-setpoint (or how to apply OPF-setpoints to the generators otherwise?).

Btw: your reply-speed is OUTSTANDING, thanks a lot for your patience and support :)

**Comment by cuihantao** [comment]
You are welcome. Please check the Examples section of the documentation and especially the one on Pandapower.

Please post specific questions in the Discussion board.

Regards,
Hantao Cui
