### ISSUE TITLE
Line v2 property identical to v1 property

### ISSUE THREAD

**Issue by rwl** [cuihantao/andes#8]
Should the last line of the v2 property read:

```python
return polar(Vm[self.a2], Va[self.a2])
```

Otherwise, it is identical to the v1 property above.

https://github.com/cuihantao/andes/blob/6818dcc86bd7e1a5028b5be1deee3d6b4171c540/andes/models/line.py#L384-L396

**Comment by cuihantao** [comment]
Thanks for reporting the issue. Yes, it should be `v2` and `a2` in the `v2` property. 
I had it fixed in my other fork, and I'll push it shortly.

**Comment by cuihantao** [comment]
Pushed fixes to the master branch. I'm going to close the Issue, but feel free to let me know if there is any other issue. 
By the way, I'm planning for some major updates. Is there any technique or repository that you find interesting and worth implementing?

**Comment by rwlincoln** [comment]
>By the way, I'm planning for some major updates. Is there any technique or repository that you find interesting and worth implementing?

It would be interesting to implement the CGMES models:

https://cgmes.github.io/CGMES-v2_4_15/DynamicsProfile-v2_4_15-7Aug2014.html

There is a project on the CIM UG site with spreadsheets of results uploaded by DIgSILENT, EUROSTAG, NEPLAN, NETOMAC, PTI and SICRE:

https://cimug.ucaiug.org/Groups/ENTSO-E_IOP/CGMESdynamics/default.aspx

I wouldn't recommend going to the effort of parsing the CIM RDF/XML files. The results are based on a simple two bus test case described in:

https://www.entsoe.eu/fileadmin/user_upload/_library/publications/entsoe/RG_SOC_CE/131127_Controller_Test_Report.pdf

I implemented it in PYPOWER a while back:

```python
from numpy import array
from math import sin, acos, sqrt

def case2():
    ppc = {"version": '2'}

    ##-----  Power Flow Data  -----##
    ## system MVA base
    ppc["baseMVA"] = 100.0

    # Negative load representing PQ gen at 0.95pu
    Sg = 500.0
    pf = 0.95
    theta = acos(pf)
    Pg = -Sg*pf
    Qg = -Sg*sin(theta)

    # Ref bus rated voltage differs from tfmr HV-side
    Vb = 380.0

    ## bus data
    # bus_i type Pd Qd Gs Bs area Vm Va baseKV zone Vmax Vmin
    ppc["bus"] = array([
      [1, 3, 475, 76, 0, 0, 1, 1.05, 0, Vb, 1, 1.05, 1.05],
      [2, 1, Pg, Qg, 0, 0, 1, 0.9917, 9.2327, 21, 1, 1.05, 0.95]
    ])

    ## generator data
    # bus, Pg, Qg, Qmax, Qmin, Vg, mBase, status, Pmax, Pmin
    ppc["gen"] = array([
      [1, 0, 0, 100, -100, 1.05, 100, 1, 200, 0]
    ])

    # Tfmr impedances are relative to HV-side (419kV).
    Sb_tr = 500
    Vb_hv = 380

    # Convert to system base.
    c = (Vb_hv**2 * ppc['baseMVA']) / (Vb**2 * Sb_tr)
    r_pu = (0.15/100)*c
    z_pu = (16.0/100)*c
    x_pu = sqrt(z_pu**2 - r_pu**2)

    # Off-nominal rated voltage on the HV side of the transformer requires
    # adjustment to the tap ratio of the branch element.
    tap = 419.0/380.0

    ## branch data
    #fbus, tbus, r, x, b, rateA, rateB, rateC, ratio, angle, status
    ppc["branch"] = array([
      [1, 2, r_pu, x_pu, 0.0, 500, 0, 0, tap, 0, 1]
    ])

    return ppc
```

Is this something you might be interested in? It would be a good way to verify the Andes models.

**Comment by cuihantao** [comment]
It's pretty important to verify the models in Andes, but the efforts needed may also be considerable.

I was hunting for automated tools to make modeling easier. One consideration is to preserve model equations alongside the numerical function calls. The goal is to generate (most of the) function calls and block diagrams from the equations.

The second technique is Modelica and FMU. I was tinkering with component-wise FMUs generated from the OpenIPSL project. However, given the simultaneous solution approach Andes is using, I might have to iteration among the algebraic function calls across FMUs.
