### ISSUE TITLE
Frequencies in Eigenanalysis report mixed up

### ISSUE THREAD

**Issue by rwl** [cuihantao/andes#80]
The damped and undamped frequency calculations in the `eig.py` report method may be the wrong way round.

https://github.com/cuihantao/andes/blob/06dca9249ee1d98025ae47f0e4afdce6072304dd/andes/routines/eig.py#L311-L312

Should the damped frequency use the imaginary part?  The mix up may be due to the slightly confusing way these equations are defined in "Power System Modeling and Scripting". It might be worth double checking with the book.

**Comment by cuihantao** [comment]
Richard,

Thanks a lot for pointing out. I investigate this issue over the weekend. 

By the way, your recent work MATPOWER.app is very impressive.

**Comment by cuihantao** [comment]
@rwl I made two mistakes by flipping them in the calculation and the print out. That's why the report shows correctly that undamped freq >= damped freq. Going to correct it in a minute.

**Comment by cuihantao** [comment]
Merged the change. I'm going to close this issue. Feel free to reopen or comment.
